#!/bin/sh
# script pour importer une base de prod
# prend en argument un fichier sql exporté depuis la prod
# TODO: faire une section "conf" qui permet de sepcifier les hostnama, etc.

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
fi

echo "Import begins..."

#backup au cas où
mysqldump -uroot -proot thebeautyst > latest-dev.sql
echo "Dump ok"

#effacer la base
mysql -uroot -proot -Bse "drop database thebeautyst; create database thebeautyst;"
echo "Database deleted"

#importer la base passée en param
mysql -uroot -proot thebeautyst < $1
echo "Prod database imported"

#mise à jour du domaine
mysql -uroot -proot -Bse "UPDATE  \`thebeautyst\`.\`core_config_data\` SET  \`value\` =  'http://pkdick.thebeautyst.org/' WHERE  \`core_config_data\`.\`config_id\` =11; UPDATE  \`thebeautyst\`.\`core_config_data\` SET  \`value\` =  'http://pkdick.thebeautyst.org/' WHERE  \`core_config_data\`.\`config_id\` =12; UPDATE  \`thebeautyst\`.\`wp_options\` SET  \`option_value\` =  'http://pkdick.thebeautyst.org/conseils-beaute' WHERE  \`wp_options\`.\`option_id\` =37; UPDATE  \`thebeautyst\`.\`wp_options\` SET  \`option_value\` =  'http://pkdick.thebeautyst.org/conseils-beaute' WHERE  \`wp_options\`.\`option_id\` =1;"
echo "Config updated"

#fin
echo "Import finished."
